"""Initial revision

Revision ID: 453f6242792c
Revises:
Create Date: 2021-10-22 18:33:48.240083

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '453f6242792c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('windboxes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_windboxes_id'), 'windboxes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_windboxes_id'), table_name='windboxes')
    op.drop_table('windboxes')
    # ### end Alembic commands ###
